### ISSUE TITLE
Keyboard css imported twice

### ISSUE THREAD

**Issue by dika-pro** [nsftx/nsoft-components#72]
First inside `styleguide.keyboard.scss` (`@import "./keyboard";`) then again inside `styleguide.scss` (`@import "_keyboard";`)

**Comment by aldinezi** [comment]
It may seem as bug to you, but this `styleguide.keyboard.scss` was created to separate component's own styling, so we import this one inside the component itself. That way, we ensured that built WC component has only it's own style embedded, rather than embedding the whole styleguide.

You have some other idea? @dika-pro

**Comment by dika-pro** [comment]
What if there is requirement that  `styleguide.keyboard.scss` imported from project that is including keyboard as standalone lib?

**Comment by aldinezi** [comment]
If we are about to focus on WC builds, and prioritize the usage of WCs, then it is not really that good idea. 
Also, including it twice there, I guess it should not be duplicated in the resulting css, regarding the tree-shaking functionality of webpack.
